# Generated by Django 5.2.4 on 2025-07-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('print_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('gstin', models.CharField(max_length=20)),
                ('gst_type', models.CharField(max_length=50)),
                ('pan_no', models.CharField(max_length=20)),
                ('fssai_no', models.CharField(max_length=20)),
                ('trade_license_no', models.CharField(max_length=50)),
                ('invoice_prefix', models.CharField(max_length=10)),
                ('invoice_start_num', models.IntegerField(blank=True, null=True)),
                ('default_tax_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_no', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('year_from', models.DateField(blank=True, null=True)),
                ('year_to', models.DateField(blank=True, null=True)),
                ('auto_backup', models.BooleanField(default=False)),
                ('daily_backup_path', models.CharField(blank=True, max_length=255, null=True)),
                ('printer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('auto_logout_minutes', models.IntegerField(default=0)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('is_sunday_open', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], max_length=10)),
                ('admin_password', models.CharField(blank=True, max_length=255, null=True)),
                ('confirm_password', models.CharField(blank=True, max_length=255, null=True)),
                ('password_hash', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
