# Generated by Django 5.2.4 on 2026-02-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfig',
            name='alert_recipients',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
