# Generated by Django 5.2.4 on 2025-07-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0002_companydetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='supplier_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
