# Generated by Django 5.2.4 on 2025-07-08 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0002_itembarcode_whole_price1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='P_unit',
        ),
    ]
