# Generated by Django 5.2.4 on 2025-07-04 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0002_product_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
