# Generated by Django 5.2.4 on 2026-02-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0003_emaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfig',
            name='alert_enabled',
            field=models.BooleanField(default=True),
        ),
    ]

