# Generated by Django 5.2.4 on 2025-07-08 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0003_remove_item_p_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='P_unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
