# Generated by Django 5.2.4 on 2026-02-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0004_emailconfig_alert_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfig',
            name='access_denied_alert_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emailconfig',
            name='low_stock_alert_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emailconfig',
            name='no_stock_alert_enabled',
            field=models.BooleanField(default=True),
        ),
    ]

