# Generated by Django 5.2.4 on 2025-07-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0004_item_p_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supplier_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
