# Generated by Django 5.2.4 on 2026-02-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MahilMartPOS_App", "0005_emailconfig_alert_toggles"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashierpermission",
            name="allow_license_manager",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="supervisorpermission",
            name="allow_license_manager",
            field=models.BooleanField(default=False),
        ),
    ]

