# Generated by Django 5.2.4 on 2025-07-08 08:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0007_remove_purchase_discount_remove_purchase_tax_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='date',
        ),
        migrations.AddField(
            model_name='purchase',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='supplier_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
