# Generated by Django 5.2.4 on 2025-07-08 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0008_remove_purchase_date_purchase_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseitem',
            old_name='supplier_id',
            new_name='supplier_unique_id',
        ),
    ]
