# Generated by Django 5.2.4 on 2025-07-08 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0009_rename_supplier_id_purchaseitem_supplier_unique_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseitem',
            old_name='supplier_unique_id',
            new_name='supplier_id',
        ),
    ]
