# Generated by Django 5.2.4 on 2025-07-08 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0010_rename_supplier_unique_id_purchaseitem_supplier_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='supplier_id',
            new_name='supplier_code',
        ),
    ]
