# Generated by Django 5.2.4 on 2025-07-08 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0011_rename_supplier_id_supplier_supplier_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='supplier_code',
            new_name='supplier_id',
        ),
    ]
