# Generated by Django 5.2.4 on 2025-07-09 07:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0013_remove_product_category_remove_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='batch_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='purchased_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
