# Generated by Django 5.2.4 on 2025-07-09 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0014_purchaseitem_batch_no_purchaseitem_expiry_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseitem',
            old_name='supplier_id',
            new_name='supplier_oid',
        ),
    ]
