# Generated by Django 5.2.4 on 2025-07-09 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0015_rename_supplier_id_purchaseitem_supplier_oid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseitem',
            old_name='supplier_oid',
            new_name='supplier_id',
        ),
    ]
