# Generated by Django 5.2.4 on 2025-07-09 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0016_rename_supplier_oid_purchaseitem_supplier_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseitem',
            old_name='batch_no',
            new_name='batch_no1',
        ),
        migrations.RenameField(
            model_name='purchaseitem',
            old_name='expiry_date',
            new_name='expiry_date1',
        ),
        migrations.RenameField(
            model_name='purchaseitem',
            old_name='purchased_at',
            new_name='purchased_at1',
        ),
    ]
