# Generated by Django 5.2.4 on 2025-07-09 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0017_rename_batch_no_purchaseitem_batch_no1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseitem',
            old_name='batch_no1',
            new_name='batch_no',
        ),
        migrations.RenameField(
            model_name='purchaseitem',
            old_name='expiry_date1',
            new_name='expiry_date',
        ),
        migrations.RenameField(
            model_name='purchaseitem',
            old_name='purchased_at1',
            new_name='purchased_at',
        ),
    ]
