# Generated by Django 5.2.4 on 2025-07-09 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0019_product_brand_product_code_product_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MahilMartPOS_App.item'),
        ),
    ]
