# Generated by Django 5.2.4 on 2025-07-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0020_alter_product_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='previous_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='total_qty',
            field=models.IntegerField(default=0),
        ),
    ]
