# Generated by Django 5.2.4 on 2025-07-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0021_purchaseitem_previous_qty_purchaseitem_total_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='previous_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='total_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
