# Generated by Django 5.2.4 on 2025-07-11 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0022_alter_purchaseitem_previous_qty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_name', models.CharField(max_length=100)),
                ('print_name', models.CharField(max_length=100)),
                ('tax_type', models.CharField(max_length=20)),
                ('effect_form', models.DateField()),
                ('rounded', models.IntegerField(default=0)),
                ('gst_type', models.CharField(max_length=50)),
                ('gst_percent', models.FloatField()),
                ('round_type', models.CharField(max_length=20)),
                ('cess_percent', models.FloatField(default=0.0)),
                ('sgst_percent', models.FloatField()),
                ('sgst_sales_account_1', models.CharField(max_length=100)),
                ('sgst_sales_account_2', models.CharField(max_length=100)),
                ('sgst_sales_return_1', models.CharField(max_length=100)),
                ('sgst_sales_return_2', models.CharField(max_length=100)),
                ('sgst_purchase_account_1', models.CharField(max_length=100)),
                ('sgst_purchase_account_2', models.CharField(max_length=100)),
                ('sgst_purchase_return_1', models.CharField(max_length=100)),
                ('sgst_purchase_return_2', models.CharField(max_length=100)),
                ('cgst_percent', models.FloatField()),
                ('cgst_sales_account_1', models.CharField(max_length=100)),
                ('cgst_sales_account_2', models.CharField(max_length=100)),
                ('cgst_sales_return_1', models.CharField(max_length=100)),
                ('cgst_sales_return_2', models.CharField(max_length=100)),
                ('cgst_purchase_account_1', models.CharField(max_length=100)),
                ('cgst_purchase_account_2', models.CharField(max_length=100)),
                ('cgst_purchase_return_1', models.CharField(max_length=100)),
                ('cgst_purchase_return_2', models.CharField(max_length=100)),
            ],
        ),
    ]
