# Generated by Django 5.2.4 on 2025-07-11 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0023_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tax',
            name='gst_type',
        ),
        migrations.AddField(
            model_name='item',
            name='gst_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MahilMartPOS_App.tax'),
        ),
    ]
