# Generated by Django 5.2.4 on 2025-07-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0024_remove_tax_gst_type_item_gst_percent_alter_item_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='gst_percent',
        ),
        migrations.AddField(
            model_name='tax',
            name='gst_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='tax',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
