# Generated by Django 5.2.4 on 2025-07-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0025_remove_item_gst_percent_tax_gst_type_alter_item_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='gst_percent',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
