# Generated by Django 5.2.4 on 2025-07-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0026_alter_tax_gst_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tax',
            name='gst_percent',
            field=models.FloatField(),
        ),
    ]
