# Generated by Django 5.2.4 on 2025-07-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0027_alter_item_tax_alter_tax_gst_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='invoice',
            field=models.CharField(default='INV-0000', max_length=100),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='invoice',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
