# Generated by Django 5.2.4 on 2025-07-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0028_purchase_invoice_purchaseitem_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='invoice',
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
