# Generated by Django 5.2.4 on 2025-07-14 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0029_remove_purchase_invoice_remove_purchaseitem_invoice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseitem',
            old_name='invoice_id',
            new_name='invoice_no',
        ),
    ]
