# Generated by Django 5.2.4 on 2025-07-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0030_rename_invoice_id_purchaseitem_invoice_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='item_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
