# Generated by Django 5.2.4 on 2025-07-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0033_stockadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustment',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='item_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='item_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='supplier_id_snapshot',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
