# Generated by Django 5.2.4 on 2025-07-17 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0034_stockadjustment_invoice_no_stockadjustment_item_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockadjustment',
            name='invoice_no',
        ),
        migrations.RemoveField(
            model_name='stockadjustment',
            name='item_code',
        ),
        migrations.RemoveField(
            model_name='stockadjustment',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='stockadjustment',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='stockadjustment',
            name='supplier_id_snapshot',
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='adjustment_type',
            field=models.CharField(choices=[('add', 'Add Stock'), ('subtract', 'Subtract Stock')], max_length=10),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='purchase_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MahilMartPOS_App.purchaseitem'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='reason',
            field=models.CharField(choices=[('damaged', 'Damaged'), ('lost', 'Lost'), ('expired', 'Expired'), ('inventory_correction', 'Inventory Correction'), ('manual_adjustment', 'Manual Adjustment')], default='manual_adjustment', max_length=30),
        ),
    ]
