# Generated by Django 5.2.4 on 2025-07-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0036_stockadjustment_code_stockadjustment_invoice_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockadjustment',
            name='supplier_id',
            field=models.CharField(max_length=100),
        ),
    ]
