# Generated by Django 5.2.4 on 2025-07-17 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0037_alter_stockadjustment_supplier_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockadjustment',
            name='code',
        ),
        migrations.RemoveField(
            model_name='stockadjustment',
            name='invoice_no',
        ),
        migrations.RemoveField(
            model_name='stockadjustment',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='stockadjustment',
            name='supplier_id',
        ),
    ]
