# Generated by Django 5.2.4 on 2025-07-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0038_remove_stockadjustment_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustment',
            name='code',
            field=models.CharField(default='UNKNOWN', max_length=100),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='invoice_no',
            field=models.CharField(default='UNKNOWN', max_length=100),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='item_name',
            field=models.CharField(default='UNKNOWN', max_length=255),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='supplier_code',
            field=models.CharField(default='UNKNOWN', max_length=100),
        ),
    ]
