# Generated by Django 5.2.4 on 2025-07-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0039_stockadjustment_code_stockadjustment_invoice_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockadjustment',
            name='supplier_code',
            field=models.CharField(default='UNKNOWN', max_length=20),
        ),
    ]
