# Generated by Django 5.2.4 on 2025-07-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0040_alter_stockadjustment_supplier_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustment',
            name='batch_no',
            field=models.CharField(default='UNKNOWN', max_length=100),
        ),
    ]
