# Generated by Django 5.2.4 on 2025-07-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0041_stockadjustment_batch_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
