# Generated by Django 5.2.4 on 2025-07-17 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0042_purchaseitem_brand_purchaseitem_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MahilMartPOS_App.item')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MahilMartPOS_App.purchase')),
                ('purchase_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MahilMartPOS_App.purchaseitem')),
            ],
        ),
    ]
