# Generated by Django 5.2.4 on 2025-07-17 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0044_delete_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100)),
                ('group', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(max_length=50)),
                ('batch_no', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_no', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.FloatField(default=0)),
                ('previous_qty', models.FloatField(default=0)),
                ('total_qty', models.FloatField(default=0)),
                ('unit_price', models.FloatField(default=0)),
                ('total_price', models.FloatField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('tax', models.FloatField(default=0)),
                ('net_price', models.FloatField(default=0)),
                ('mrp_price', models.FloatField(default=0)),
                ('whole_price', models.FloatField(default=0)),
                ('whole_price_2', models.FloatField(default=0)),
                ('sale_price', models.FloatField(default=0)),
                ('purchased_at', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MahilMartPOS_App.item')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MahilMartPOS_App.purchase')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MahilMartPOS_App.supplier')),
            ],
        ),
    ]
