# Generated by Django 5.2.4 on 2025-07-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0045_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseBulk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=50)),
                ('batch_no', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_no', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.FloatField()),
                ('unit_price', models.FloatField()),
                ('total_price', models.FloatField()),
                ('discount', models.FloatField(default=0)),
                ('tax', models.FloatField(default=0)),
                ('net_price', models.FloatField()),
                ('mrp_price', models.FloatField(blank=True, null=True)),
                ('whole_price', models.FloatField(blank=True, null=True)),
                ('whole_price_2', models.FloatField(blank=True, null=True)),
                ('sale_price', models.FloatField(blank=True, null=True)),
                ('purchased_at', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('purchase_id', models.IntegerField(blank=True, null=True)),
                ('supplier_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
