# Generated by Django 5.2.4 on 2025-07-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0046_purchasebulk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='invoice_no',
        ),
        migrations.AddField(
            model_name='purchase',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
