# Generated by Django 5.2.4 on 2025-07-25 12:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0047_remove_purchaseitem_invoice_no_purchase_invoice_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('expenseid', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('category', models.CharField(choices=[('Staff Salaries', 'Staff Salaries'), ('Water', 'Water Bill'), ('Internet', 'Internet Bill'), ('Electricity', 'Electricity Bill'), ('Rent/Lease', 'Rent/Lease'), ('Maintenance', 'Maintenance'), ('Office Supplies', 'Office Supplies'), ('Software Maintenance', 'Software Maintenance'), ('Marketing', 'Marketing'), ('Transport/Delivery', 'Transport/Delivery'), ('Miscellaneous', 'Miscellaneous')], max_length=100)),
                ('category_detail', models.CharField(blank=True, max_length=200, null=True)),
                ('paid_to', models.CharField(blank=True, max_length=100, null=True)),
                ('paymentmode', models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank', 'Bank'), ('upi', 'UPI'), ('cheque', 'Cheque')], max_length=10, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('refno', models.CharField(blank=True, max_length=100, null=True)),
                ('reorderedby', models.CharField(blank=True, max_length=100, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='expense_attachments/')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('date_of_order', models.DateTimeField(default=django.utils.timezone.now)),
                ('expected_delivery_datetime', models.DateTimeField()),
                ('delivery', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_order_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('advance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('full_amount_paid', models.BooleanField(default=False)),
                ('payment_type', models.CharField(choices=[('cash', 'Cash'), ('gpay', 'GPay'), ('card', 'Card'), ('credit', 'Credit')], max_length=10)),
                ('order_status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('elapsed', 'Elapsed'), ('cancelled', 'Cancelled')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('bill_no', models.CharField(max_length=20)),
                ('customer', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('cashier', models.CharField(max_length=50)),
                ('payment_mode', models.CharField(max_length=50)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('qtn_no', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=200)),
                ('qty', models.IntegerField()),
                ('mrsp', models.FloatField()),
                ('selling_price', models.FloatField()),
                ('total_amount', models.FloatField()),
                ('points_earned', models.FloatField(default=0)),
                ('to', models.CharField(max_length=100)),
                ('bill_no', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('date_joined', models.DateField()),
                ('bill_type', models.CharField(max_length=100)),
                ('sale_type', models.CharField(max_length=100)),
                ('counter', models.CharField(max_length=100)),
                ('order_no', models.CharField(blank=True, max_length=100)),
                ('cell', models.CharField(max_length=20)),
                ('received', models.FloatField(default=0)),
                ('balance', models.FloatField(default=0)),
                ('discount', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='MahilMartPOS_App.order')),
            ],
        ),
    ]
