# Generated by Django 5.2.4 on 2025-07-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0048_expense_order_payment_quotation_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='full_amount_paid',
        ),
        migrations.AddField(
            model_name='order',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
