# Generated by Django 5.2.4 on 2025-07-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0049_remove_order_full_amount_paid_order_paid_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='phone',
        ),
        migrations.AddField(
            model_name='billing',
            name='cell',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='bill_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='billing',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='date_joined',
            field=models.DateField(blank=True, null=True),
        ),
    ]
