# Generated by Django 5.2.4 on 2025-07-26 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0050_remove_billing_phone_billing_cell_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='phone',
            new_name='cell',
        ),
    ]
