# Generated by Django 5.2.4 on 2025-07-26 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0051_rename_phone_customer_cell'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
