# Generated by Django 5.2.4 on 2025-07-26 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0052_delete_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quotation',
        ),
    ]
