# Generated by Django 5.2.4 on 2025-07-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0053_delete_quotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('qtn_no', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=200)),
                ('qty', models.IntegerField()),
                ('mrsp', models.FloatField()),
                ('selling_price', models.FloatField()),
                ('total_amount', models.FloatField()),
                ('points_earned', models.FloatField(default=0)),
                ('to', models.CharField(max_length=100)),
                ('bill_no', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('date_joined', models.DateField()),
                ('bill_type', models.CharField(max_length=100)),
                ('sale_type', models.CharField(max_length=100)),
                ('counter', models.CharField(max_length=100)),
                ('order_no', models.CharField(blank=True, max_length=100)),
                ('cell', models.CharField(max_length=20)),
                ('received', models.FloatField(default=0)),
                ('balance', models.FloatField(default=0)),
                ('discount', models.FloatField(default=0)),
            ],
        ),
    ]
