# Generated by Django 5.2.4 on 2025-07-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0054_quotation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='code',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='mrsp',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='selling_price',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='sno',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='total_items',
        ),
        migrations.AddField(
            model_name='billing',
            name='item_details',
            field=models.JSONField(default=list),
        ),
    ]
