# Generated by Django 5.2.4 on 2025-07-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0055_remove_billing_code_remove_billing_item_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='code',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='mrsp',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='selling_price',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='sno',
        ),
        migrations.AddField(
            model_name='quotation',
            name='item_details',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
