# Generated by Django 5.2.4 on 2025-07-28 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0056_remove_quotation_code_remove_quotation_item_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='to',
        ),
    ]
