# Generated by Django 5.2.4 on 2025-07-28 07:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0057_remove_quotation_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='quotation',
            name='points',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='quotation',
            name='to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='total_items',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quotation',
            name='total_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='bill_no',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='bill_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='cell',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='counter',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='item_details',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='order_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='qtn_no',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='sale_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='total_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
