# Generated by Django 5.2.4 on 2025-07-28 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0058_quotation_created_at_quotation_points_quotation_to_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quotation',
        ),
    ]
