# Generated by Django 5.2.4 on 2025-07-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0059_delete_quotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtn_no', models.CharField(max_length=20, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('cell', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(blank=True, null=True)),
                ('date_joined', models.DateField()),
                ('sale_type', models.CharField(max_length=50)),
                ('bill_type', models.CharField(max_length=50)),
                ('counter', models.CharField(max_length=50)),
                ('order_no', models.CharField(blank=True, max_length=50, null=True)),
                ('received', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('points', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('points_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('items', models.JSONField()),
            ],
        ),
    ]
