# Generated by Django 5.2.4 on 2025-07-28 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0060_quotation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='order_no',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='received',
        ),
    ]
