# Generated by Django 5.2.4 on 2025-07-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0061_remove_quotation_balance_remove_quotation_order_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='hsn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
