# Generated by Django 5.2.4 on 2025-07-29 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0062_item_hsn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='hsn',
        ),
    ]
