# Generated by Django 5.2.4 on 2025-07-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0063_remove_item_hsn'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='hsn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
