# Generated by Django 5.2.4 on 2025-07-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0064_purchaseitem_hsn'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='hsn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
