# Generated by Django 5.2.4 on 2025-07-29 09:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0065_inventory_hsn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='purchased_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='purchased_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
