# Generated by Django 5.2.4 on 2025-07-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0066_alter_inventory_purchased_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='billing',
            name='points_earned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
