# Generated by Django 5.2.4 on 2025-07-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0067_alter_billing_points_alter_billing_points_earned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='points',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='billing',
            name='points_earned',
            field=models.FloatField(default=0.0),
        ),
    ]
