# Generated by Django 5.2.4 on 2025-07-29 12:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0068_alter_billing_points_alter_billing_points_earned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='purchased_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
