# Generated by Django 5.2.4 on 2025-07-30 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0069_alter_purchaseitem_purchased_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
