# Generated by Django 5.2.4 on 2025-07-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0070_billing_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='MRSP',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='P_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='cost_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='sale_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='whole_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='whole_rate_2',
            field=models.FloatField(),
        ),
    ]
