# Generated by Django 5.2.4 on 2025-07-31 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0071_alter_item_mrsp_alter_item_p_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='total_quantity',
            field=models.FloatField(default=0),
        ),
    ]
