# Generated by Django 5.2.4 on 2025-07-31 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0072_purchase_total_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='total_quantity',
            new_name='total_products',
        ),
    ]
