# Generated by Django 5.2.4 on 2025-07-31 08:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0073_rename_total_quantity_purchase_total_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustment',
            name='adjusted_net_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='adjusted_total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
