# Generated by Django 5.2.4 on 2025-07-31 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0075_remove_stockadjustment_adjusted_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustment',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MahilMartPOS_App.purchase'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
