# Generated by Django 5.2.4 on 2025-07-31 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0076_stockadjustment_purchase_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='invoice_no',
        ),
    ]
