# Generated by Django 5.2.4 on 2025-07-31 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0077_remove_inventory_invoice_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustment',
            name='unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
