# Generated by Django 5.2.4 on 2025-07-31 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0078_stockadjustment_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='split_unit',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='split_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
