# Generated by Django 5.2.4 on 2025-07-31 13:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0079_inventory_split_unit_purchaseitem_split_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustment',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
