# Generated by Django 5.2.4 on 2025-08-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0080_stockadjustment_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='remarks',
            field=models.TextField(blank=True, default='N/A'),
        ),
    ]
