# Generated by Django 5.2.4 on 2025-08-04 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0081_inventory_remarks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchaseBulk',
        ),
        migrations.AddField(
            model_name='inventory',
            name='split_unit_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='split_unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
