# Generated by Django 5.2.4 on 2025-08-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0082_delete_purchasebulk_inventory_split_unit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='unit_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='unit_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
