# Generated by Django 5.2.4 on 2025-08-05 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0083_inventory_unit_quantity_purchaseitem_unit_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='unit_quantity',
            new_name='unit_qty',
        ),
        migrations.RenameField(
            model_name='purchaseitem',
            old_name='unit_quantity',
            new_name='unit_qty',
        ),
    ]
