# Generated by Django 5.2.4 on 2025-08-06 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0084_rename_unit_quantity_inventory_unit_qty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='address',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='cell',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='email',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='item_details',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='name',
        ),
        migrations.AddField(
            model_name='billing',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MahilMartPOS_App.customer'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='bill_no',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='BillingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=50)),
                ('qty', models.FloatField()),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='MahilMartPOS_App.billing')),
            ],
        ),
    ]
