# Generated by Django 5.2.4 on 2025-08-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0086_billing_created_at_billingitem_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustment',
            name='split_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
