# Generated by Django 5.2.4 on 2025-08-06 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0087_stockadjustment_split_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='remarks',
            new_name='Status',
        ),
    ]
