# Generated by Django 5.2.4 on 2025-08-06 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0088_rename_remarks_inventory_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='Status',
            new_name='status',
        ),
    ]
