# Generated by Django 5.2.4 on 2025-08-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0089_rename_status_inventory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='status',
            field=models.CharField(default='in_stock', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='status',
            field=models.CharField(default='in_stock', max_length=20),
        ),
    ]
