# Generated by Django 5.2.4 on 2025-08-09 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0090_purchaseitem_status_alter_inventory_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_reason', models.TextField()),
                ('total_return_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MahilMartPOS_App.billing')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MahilMartPOS_App.customer')),
            ],
        ),
        migrations.CreateModel(
            name='SaleReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=100)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('return_qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('return_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MahilMartPOS_App.billingitem')),
                ('sale_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MahilMartPOS_App.salereturn')),
            ],
        ),
    ]
