# Generated by Django 5.2.4 on 2025-08-13 06:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0092_inventory_cost_price_purchaseitem_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustment',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
