# Generated by Django 5.2.4 on 2025-08-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0093_stockadjustment_cost_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='decimals',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
