# Generated by Django 5.2.4 on 2025-08-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0094_alter_unit_decimals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='decimals',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
