# Generated by Django 5.2.4 on 2025-08-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0096_inventory_taxable_price_purchaseitem_taxable_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='status',
            field=models.CharField(default='counter_bill', max_length=50),
        ),
    ]
