# Generated by Django 5.2.4 on 2025-08-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0097_billing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='order_bill_no',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
