# Generated by Django 5.2.4 on 2025-08-14 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0098_billing_order_bill_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing',
            old_name='status',
            new_name='status_on',
        ),
    ]
