# Generated by Django 5.2.4 on 2025-08-14 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0099_rename_status_billing_status_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='order_bill_no',
        ),
    ]
