# Generated by Django 5.2.4 on 2025-08-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0100_remove_billing_order_bill_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qtn_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
