# Generated by Django 5.2.4 on 2025-08-15 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0101_order_qtn_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='bill_attachment',
            field=models.FileField(blank=True, null=True, upload_to='supplier_bills/'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='fssai_number',
            field=models.CharField(blank=True, default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='supplier',
            name='status',
            field=models.CharField(blank=True, default='N/A', max_length=20),
        ),
    ]
