# Generated by Django 5.2.4 on 2025-08-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0102_supplier_bill_attachment_supplier_fssai_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
    ]
