# Generated by Django 5.2.4 on 2025-08-15 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0103_alter_supplier_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='bill_attachment',
        ),
    ]
