# Generated by Django 5.2.4 on 2025-08-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0104_remove_supplier_bill_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchase',
            name='bill_attachment',
            field=models.FileField(blank=True, null=True, upload_to='bill_attachments/'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='outstanding_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Bank Transfer', 'Bank Transfer'), ('UPI', 'UPI'), ('Cheque', 'Cheque'), ('Credit', 'Credit'), ('Partial Credit', 'Partial Credit')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
