# Generated by Django 5.2.4 on 2025-08-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0105_purchase_amount_paid_purchase_bill_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
    ]
