# Generated by Django 5.2.4 on 2025-08-18 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0107_purchase_discount_purchase_sub_total_purchase_tax'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='sub_total',
            new_name='subtotal',
        ),
    ]
