# Generated by Django 5.2.4 on 2025-08-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0108_rename_sub_total_purchase_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='payment_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
