# Generated by Django 5.2.4 on 2025-08-18 10:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0110_purchasepayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasepayment',
            name='payment_date',
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='paid_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='MahilMartPOS_App.supplier'),
        ),
    ]
