# Generated by Django 5.2.4 on 2025-08-18 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0111_remove_purchasepayment_payment_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasepayment',
            old_name='paid_at',
            new_name='payment_date',
        ),
    ]
