# Generated by Django 5.2.4 on 2025-08-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0112_rename_paid_at_purchasepayment_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasepayment',
            name='balance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
