# Generated by Django 5.2.4 on 2025-08-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0113_purchasepayment_balance_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasepayment',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
