# Generated by Django 5.2.4 on 2025-08-20 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0114_purchasepayment_invoice_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
