# Generated by Django 5.2.4 on 2025-08-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0115_customer_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='remarks',
            field=models.TextField(blank=True, default='billing_entry'),
        ),
    ]
