# Generated by Django 5.2.4 on 2025-08-22 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0117_billing_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('ADDED', 'Added'), ('REMOVED', 'Removed'), ('UPDATED', 'Updated')], max_length=20)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('mrp_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('whole_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('whole_price_2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('net_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('batch_no', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('purchased_at', models.DateTimeField(blank=True, null=True)),
                ('previous_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('group', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('hsn', models.CharField(blank=True, max_length=50, null=True)),
                ('split_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('split_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unit_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('taxable_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tracked_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MahilMartPOS_App.item')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='MahilMartPOS_App.purchase')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MahilMartPOS_App.supplier')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MahilMartPOS_App.user')),
            ],
        ),
    ]
