# Generated by Django 5.2.4 on 2025-08-22 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0118_purchasetracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasetracking',
            name='updated_by',
        ),
    ]
