# Generated by Django 5.2.4 on 2025-08-22 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0119_remove_purchasetracking_updated_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchaseTracking',
        ),
    ]
