# Generated by Django 5.2.4 on 2025-08-22 11:48

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0121_purchaseadjustmenttracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseItemAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('added', 'Added'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('returned', 'Returned')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MahilMartPOS_App.item')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MahilMartPOS_App.purchase')),
                ('purchase_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MahilMartPOS_App.purchaseitem')),
            ],
        ),
        migrations.DeleteModel(
            name='PurchaseAdjustmentTracking',
        ),
    ]
