# Generated by Django 5.2.4 on 2025-08-22 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0123_purchaseadjustmenttracking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseadjustmenttracking',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='purchaseadjustmenttracking',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='purchaseadjustmenttracking',
            name='group',
        ),
        migrations.RemoveField(
            model_name='purchaseadjustmenttracking',
            name='hsn',
        ),
        migrations.RemoveField(
            model_name='purchaseadjustmenttracking',
            name='mrp_price',
        ),
        migrations.RemoveField(
            model_name='purchaseadjustmenttracking',
            name='net_price',
        ),
        migrations.RemoveField(
            model_name='purchaseadjustmenttracking',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='purchaseadjustmenttracking',
            name='sale_price',
        ),
        migrations.RemoveField(
            model_name='purchaseadjustmenttracking',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='purchaseadjustmenttracking',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='purchaseadjustmenttracking',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='purchaseadjustmenttracking',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='purchaseadjustmenttracking',
            name='whole_price',
        ),
        migrations.RemoveField(
            model_name='purchaseadjustmenttracking',
            name='whole_price_2',
        ),
    ]
