# Generated by Django 5.2.4 on 2025-08-22 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0124_remove_purchaseadjustmenttracking_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseadjustmenttracking',
            name='previous_qty',
        ),
        migrations.RemoveField(
            model_name='purchaseadjustmenttracking',
            name='total_qty',
        ),
    ]
