# Generated by Django 5.2.4 on 2025-08-22 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0125_remove_purchaseadjustmenttracking_previous_qty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseadjustmenttracking',
            name='expiry_date',
        ),
    ]
