# Generated by Django 5.2.4 on 2025-08-22 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0126_remove_purchaseadjustmenttracking_expiry_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchaseAdjustmentTracking',
        ),
    ]
