# Generated by Django 5.2.4 on 2025-08-22 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0127_delete_purchaseadjustmenttracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseAdjustmentTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('ADDED', 'Added'), ('UPDATED', 'Updated'), ('REMOVED', 'Removed')], max_length=10)),
                ('status', models.CharField(choices=[('ADDED', 'Added'), ('UPDATED', 'Updated'), ('REMOVED', 'Removed')], max_length=10)),
                ('quantity', models.FloatField(default=0)),
                ('split_unit', models.FloatField(default=0)),
                ('split_unit_price', models.FloatField(default=0)),
                ('unit_qty', models.FloatField(default=0)),
                ('cost_price', models.FloatField(default=0)),
                ('taxable_price', models.FloatField(default=0)),
                ('batch_no', models.CharField(blank=True, max_length=50, null=True)),
                ('purchased_at', models.DateField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('item_name', models.CharField(blank=True, max_length=200, null=True)),
                ('hsn', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MahilMartPOS_App.item')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MahilMartPOS_App.purchase')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MahilMartPOS_App.supplier')),
            ],
        ),
    ]
