# Generated by Django 5.2.4 on 2025-08-22 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0128_purchaseadjustmenttracking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchaseAdjustmentTracking',
        ),
    ]
