# Generated by Django 5.2.4 on 2025-08-25 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0129_delete_purchaseadjustmenttracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseItemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_item_id', models.IntegerField()),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted')], max_length=20)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MahilMartPOS_App.item')),
                ('logged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MahilMartPOS_App.user')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MahilMartPOS_App.purchase')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MahilMartPOS_App.supplier')),
            ],
        ),
    ]
