# Generated by Django 5.2.4 on 2025-08-25 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0131_purchasetracking_delete_purchaseitemlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasetracking',
            name='change_type',
        ),
        migrations.RemoveField(
            model_name='purchasetracking',
            name='previous_qty',
        ),
        migrations.RemoveField(
            model_name='purchasetracking',
            name='total_qty',
        ),
        migrations.RemoveField(
            model_name='purchasetracking',
            name='updated_by',
        ),
    ]
