# Generated by Django 5.2.4 on 2025-08-25 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0132_remove_purchasetracking_change_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasetracking',
            name='batch_no',
        ),
        migrations.RemoveField(
            model_name='purchasetracking',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='purchasetracking',
            name='group',
        ),
        migrations.RemoveField(
            model_name='purchasetracking',
            name='mrp_price',
        ),
        migrations.RemoveField(
            model_name='purchasetracking',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='purchasetracking',
            name='unit_price',
        ),
    ]
