# Generated by Django 5.2.4 on 2025-08-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0133_remove_purchasetracking_batch_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasetracking',
            old_name='quantity',
            new_name='existing_quantity',
        ),
        migrations.AddField(
            model_name='purchasetracking',
            name='updated_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
