# Generated by Django 5.2.4 on 2025-08-28 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0135_billtype_counter_paymentmode_billing_card_amount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
