# Generated by Django 5.2.4 on 2025-08-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0136_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='HSN_SAC',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='cess_per_qty',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='points',
            field=models.BigIntegerField(),
        ),
    ]
