# Generated by Django 5.2.4 on 2025-08-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0137_alter_item_hsn_sac_alter_item_cess_per_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='HSN_SAC',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
