# Generated by Django 5.2.4 on 2025-08-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0138_alter_item_hsn_sac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
