# Generated by Django 5.2.4 on 2025-08-30 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0140_dailypurchasepayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyPurchasePayment',
        ),
    ]
