# Generated by Django 5.2.4 on 2025-08-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0142_dailypurchasepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailypurchasepayment',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
