# Generated by Django 5.2.4 on 2025-08-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0143_dailypurchasepayment_invoice_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailypurchasepayment',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
