# Generated by Django 5.2.4 on 2025-09-03 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0144_dailypurchasepayment_supplier_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
