# Generated by Django 5.2.4 on 2025-09-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0145_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeLabelSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('width_mm', models.PositiveIntegerField()),
                ('height_mm', models.PositiveIntegerField()),
                ('per_row', models.PositiveIntegerField(default=1)),
                ('per_column', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
