# Generated by Django 5.2.4 on 2025-09-08 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0146_barcodelabelsize'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemBarcode',
        ),
    ]
