# Generated by Django 5.2.4 on 2025-09-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0148_add_email_and_address_to_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='discount_amt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
