# Generated by Django 5.2.4 on 2025-09-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0149_billing_discount_amt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='discount_amt',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
