# Generated by Django 5.2.4 on 2025-09-15 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0150_alter_billing_discount_amt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='email',
        ),
    ]
