# Generated by Django 5.2.4 on 2025-09-16 06:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0152_remove_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
