# Generated by Django 5.2.4 on 2025-09-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0153_quotation_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='discount_after_total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='quotation',
            name='discount_amt',
            field=models.FloatField(default=0),
        ),
    ]
