# Generated by Django 5.2.4 on 2025-09-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0154_quotation_discount_after_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_for_one_point', models.DecimalField(decimal_places=2, default=200, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
