# Generated by Django 5.2.4 on 2025-09-18 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0156_billingconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingconfig',
            name='updated_at',
        ),
    ]
