from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls import handler403

urlpatterns = [
    path('', views.login_view, name='home'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('billing/<int:id>/', views.billing_detail_view, name='billing_detail'),
    path('billing/<int:bill_id>/items/', views.billing_items_api, name='billing_items_api'),
    path('sales-chart-data/', views.sales_chart_data, name='sales_chart_data'),
    path('billing/', views.create_invoice_view, name='billing'),
    path('ajax/get-item-info/', views.get_item_info, name='get_item_info'),     
    path('order/', views.order_view, name='order'),
    path('orders/', views.order_list, name='order_list'),
    path('order-success/', views.order_success, name='order_success'),
    path('orders/<int:order_id>/', views.order_detail, name='order_detail'),
    path('new-order/', views.create_order, name='create_order'),
    path('orders/<int:order_id>/edit/', views.edit_order, name='edit_order'),
    path('quotation/save/', views.create_quotation, name='create_quotation'),
    path('quotation/detail/<str:qtn_no>/', views.quotation_detail, name='quotation_detail'),    
    path('quotation/last/', views.get_last_quotation, name='last_quotation'),
    path('update-payment/<int:order_id>/', views.update_payment, name='update_payment'),
    path('convert-to-order/<str:qtn_no>/', views.convert_quotation_to_order, name='convert_to_order'),
    path('sale-return/', views.sale_return_view, name='sale_return'),
    path('sale-return/success/', views.sale_return_success_view, name='sale_return_success'),
    path('sale_return/detail/<int:pk>/', views.sale_return_detail, name='sale_return_detail'),
    path('sale-return-items/', views.sale_return_items_api, name='sale_return_items_api'),
    path('products/', views.products_view, name='products'),
    path('item/create', views.item_creation, name='items'),
    path('barcode',views.Item_barcode,name='item_barcode'),
    path('unit', views.Unit_creation, name='unit_creation'),
    path('group', views.Group_creation, name='group_creation'),
    path('brand', views.Brand_creation, name='brand_creation'),
    path('tax', views.Tax_creation, name='tax_creation'),    
    path('purchase/', views.purchase_view, name='purchase'),
    path('purchase_list/', views.purchase_list, name='purchase_list'),
    path('purchases/export/', views.export_purchases, name='export_purchases'),
    path('api/item/fetch/', views.fetch_item, name='fetch_item'),
    path('api/purchase/create/', views.create_purchase, name='create_purchase'),
    path('api/purchase/items/', views.fetch_purchase_items, name='fetch_purchase_items'),
    path('purchase_return/', views.purchase_return_view, name='purchase_return'),
    path('stock_adjustment/', views.stock_adjustment_view, name='stock_adjustment'),   
    path('stock_adjustments/', views.stock_adjustment_list, name='stock_adjustment_list'),
    path('split-stock/', views.split_stock_page, name='split_stock'),
    path('inventory/edit/<int:item_id>/', views.edit_bulk_item, name='edit_bulk_item'),
    path('ajax/fetch-item-info/', views.fetch_item_info, name='fetch_item_info'),
    path('inventory/', views.inventory_view, name='inventory'),
    path('product/<int:pk>/', views.product_detail, name='product_detail'), 
    path('suppliers/', views.suppliers_view, name='suppliers'),
    path('suppliers/add/', views.add_supplier, name='add_supplier'),
    path('suppliers/edit/<int:supplier_id>/', views.edit_supplier, name='edit_supplier'),
    path('suppliers/delete/<int:supplier_id>/', views.delete_supplier, name='delete_supplier'),
    path('customers/', views.customers_view, name='customers'),
    path('add-customer/', views.add_customer, name='add_customer'),
    path('submit-customer/', views.submit_customer, name='submit_customer'),
    path('payments/', views.payment_list_view, name='payment-list'),
    path('purchase_items/', views.purchase_items_view, name='purchase_items'),
    path('api/purchase-payments/<str:invoice_no>/', views.purchase_payments_api, name='purchase-payments-api'),
    path('expense/',views.create_expense,name='expense'),
    path('expense/list/', views.expense_list, name='expense_list'),
    path('user/', views.user_view, name='user'),
    path('company/', views.company_settings_view, name='company_details'),
    path('company-details/view/', views.view_company_details, name='view_company_details'),
    path('logout/', auth_views.LogoutView.as_view(next_page='home'), name='logout'),
]

handler403 = 'MahilMartPOS_App.views.custom_permission_denied_view'